# Generated by Django 6.0.2 on 2026-02-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hình ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='members',
            field=models.TextField(blank=True, help_text='Nhập tên các thành viên, cách nhau bằng dấu phẩy', verbose_name='Danh sách thành viên'),
        ),
    ]
