# Generated by Django 6.0.2 on 2026-02-12 16:16

import modelcluster.fields
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpage_image_projectpage_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Danh sách thành viên',
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='description',
            field=wagtailmarkdown.fields.MarkdownField(verbose_name='Mô tả dự án (Markdown)'),
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='members',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.member', verbose_name='Thành viên tham gia'),
        ),
    ]
