"""add image_url to blogs

Revision ID: 06940d5dc44e
Revises: 713d7426c99a
Create Date: 2026-02-28 09:58:09.451908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06940d5dc44e'
down_revision: Union[str, Sequence[str], None] = '713d7426c99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'image_url')
    # ### end Alembic commands ###
