"""add_project_details_and_members

Revision ID: 1520c599f71a
Revises: 143f437632cc
Create Date: 2026-03-01 16:03:46.302172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1520c599f71a'
down_revision: Union[str, Sequence[str], None] = '143f437632cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('features', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('technologies', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('demo_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('video_url', sa.String(), nullable=True))
    op.drop_column('projects', 'project_url')
    op.drop_column('projects', 'product_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('product_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('project_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('projects', 'video_url')
    op.drop_column('projects', 'demo_url')
    op.drop_column('projects', 'technologies')
    op.drop_column('projects', 'features')
    op.drop_table('project_members')
    # ### end Alembic commands ###
