"""add summary to blogs

Revision ID: 2180db0ee43c
Revises: 30f7a54927c6
Create Date: 2026-03-01 18:05:58.642124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2180db0ee43c'
down_revision: Union[str, Sequence[str], None] = '30f7a54927c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'summary')
    # ### end Alembic commands ###
