"""add_blog_authors_relationship

Revision ID: 35f405d62d28
Revises: 34b8bae6044a
Create Date: 2026-02-28 19:20:26.063732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f405d62d28'
down_revision: Union[str, Sequence[str], None] = '34b8bae6044a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blog_id', 'user_id')
    )
    op.drop_column('blogs', 'authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('authors', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
