"""add search_vector to blogs

Revision ID: 4206104e9f2f
Revises: 06940d5dc44e
Create Date: 2026-02-28 10:22:29.294334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4206104e9f2f'
down_revision: Union[str, Sequence[str], None] = '06940d5dc44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_blogs_search_vector', 'blogs', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    # Trigger function: auto-update search_vector on INSERT/UPDATE
    op.execute("""
        CREATE OR REPLACE FUNCTION blogs_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('simple', COALESCE(NEW.title, '')), 'A') ||
                setweight(to_tsvector('simple', COALESCE(NEW.keywords, '')), 'B') ||
                setweight(to_tsvector('simple', COALESCE(NEW.content, '')), 'C');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER blogs_search_vector_trigger
        BEFORE INSERT OR UPDATE OF title, content, keywords
        ON blogs
        FOR EACH ROW
        EXECUTE FUNCTION blogs_search_vector_update();
    """)

    # Backfill search_vector for existing rows
    op.execute("""
        UPDATE blogs SET search_vector =
            setweight(to_tsvector('simple', COALESCE(title, '')), 'A') ||
            setweight(to_tsvector('simple', COALESCE(keywords, '')), 'B') ||
            setweight(to_tsvector('simple', COALESCE(content, '')), 'C');
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS blogs_search_vector_trigger ON blogs;")
    op.execute("DROP FUNCTION IF EXISTS blogs_search_vector_update();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blogs_search_vector', table_name='blogs', postgresql_using='gin')
    op.drop_column('blogs', 'search_vector')
    # ### end Alembic commands ###
