"""Cap nhat bang events theo design moi

Revision ID: 713d7426c99a
Revises: 361c693c45d4
Create Date: 2026-02-27 19:54:30.384020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '713d7426c99a'
down_revision: Union[str, Sequence[str], None] = '361c693c45d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('events', sa.Column('registration_link', sa.String(), nullable=True))
    op.add_column('events', sa.Column('hashtags', sa.String(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('events', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.alter_column('events', 'event_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'hashtags')
    op.drop_column('events', 'registration_link')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
