"""Split events

Revision ID: a25f5f34c7a7
Revises: 27c940c93405
Create Date: 2026-02-28 10:04:12.282896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a25f5f34c7a7'
down_revision: Union[str, Sequence[str], None] = '27c940c93405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('img_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('events_date', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('register_link', sa.String(), nullable=True))
    op.add_column('events', sa.Column('hashtag', sa.String(), nullable=True))
    op.execute("UPDATE events SET event_type = 'workshop' WHERE event_type IS NULL")

    op.alter_column('events', 'event_type', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'registration_link')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'hashtags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hashtags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('registration_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('events', 'hashtag')
    op.drop_column('events', 'register_link')
    op.drop_column('events', 'events_date')
    op.drop_column('events', 'img_url')
    # ### end Alembic commands ###
