"""refactor blog keywords to separate table

Revision ID: abe728c6e179
Revises: 35f405d62d28
Create Date: 2026-02-28 20:18:16.450085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abe728c6e179"
down_revision: Union[str, Sequence[str], None] = "35f405d62d28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword_name", sa.String(length=255), nullable=False),
        sa.Column("number_blog_contain", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keywords_id"), "keywords", ["id"], unique=False)
    op.create_index(
        op.f("ix_keywords_keyword_name"), "keywords", ["keyword_name"], unique=True
    )
    op.create_table(
        "blog_keywords",
        sa.Column("blog_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blogs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keywords.id"],
        ),
        sa.PrimaryKeyConstraint("blog_id", "keyword_id"),
    )

    # --- Data Migration Start ---
    connection = op.get_bind()
    blogs = connection.execute(
        sa.text("SELECT id, keywords FROM blogs WHERE keywords IS NOT NULL")
    ).fetchall()

    keyword_map = {}  # name -> id

    for blog_id, keywords_str in blogs:
        if not keywords_str:
            continue
        keyword_names = [k.strip() for k in keywords_str.split(",") if k.strip()]
        for name in keyword_names:
            if name not in keyword_map:
                connection.execute(
                    sa.text(
                        "INSERT INTO keywords (keyword_name, number_blog_contain) VALUES (:name, 0) ON CONFLICT (keyword_name) DO NOTHING"
                    ),
                    {"name": name},
                )
                res = connection.execute(
                    sa.text("SELECT id FROM keywords WHERE keyword_name = :name"),
                    {"name": name},
                ).fetchone()
                if res:
                    keyword_map[name] = res[0]

            if name in keyword_map:
                kw_id = keyword_map[name]
                connection.execute(
                    sa.text(
                        "INSERT INTO blog_keywords (blog_id, keyword_id) VALUES (:blog_id, :kw_id) ON CONFLICT DO NOTHING"
                    ),
                    {"blog_id": blog_id, "kw_id": kw_id},
                )
                connection.execute(
                    sa.text(
                        "UPDATE keywords SET number_blog_contain = number_blog_contain + 1 WHERE id = :kw_id"
                    ),
                    {"kw_id": kw_id},
                )
    # --- Data Migration End ---

    op.execute("DROP TRIGGER IF EXISTS blogs_search_vector_trigger ON blogs")
    op.drop_column("blogs", "keywords")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blogs",
        sa.Column(
            "keywords", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("blog_keywords")
    op.drop_index(op.f("ix_keywords_keyword_name"), table_name="keywords")
    op.drop_index(op.f("ix_keywords_id"), table_name="keywords")
    op.drop_table("keywords")
    # ### end Alembic commands ###
