"""add_slug_to_blogs

Revision ID: e8e80a8914b0
Revises: 2180db0ee43c
Create Date: 2026-03-01 21:21:53.657585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8e80a8914b0"
down_revision: Union[str, Sequence[str], None] = "2180db0ee43c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column first
    op.add_column("blogs", sa.Column("slug", sa.String(length=500), nullable=True))

    # Backfill slugs for existing blogs
    from slugify import slugify as _slugify

    conn = op.get_bind()
    blogs = conn.execute(sa.text("SELECT id, title FROM blogs")).fetchall()
    for blog_id, title in blogs:
        base = _slugify(title, max_length=200)
        slug_val = f"{base}-{blog_id}" if base else str(blog_id)
        conn.execute(
            sa.text("UPDATE blogs SET slug = :slug WHERE id = :id"),
            {"slug": slug_val, "id": blog_id},
        )

    # Now create the unique index
    op.create_index(op.f("ix_blogs_slug"), "blogs", ["slug"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blogs_slug"), table_name="blogs")
    op.drop_column("blogs", "slug")
    # ### end Alembic commands ###
