# Generated by Django 6.0.2 on 2026-02-12 15:02

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_introductionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(verbose_name='Nội dung giới thiệu (Markdown)'),
        ),
    ]
